# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Emil"
license = "MIT"
licenselink = "https://github.com/emilabraham/emil/blob/master/LICENSE"
description = "An extremely minimal theme"
homepage = "https://emilabraham.com/"
tags = ["Minimal"]
features = []
min_version = "0.115.3"

[author]
  name = "Emil Abraham"
  homepage = "https://emilabraham.com/"
